import "./globals.css";
import Navbar from "@/components/Navbar";
import { dbConnect } from "@/service/connectMongo";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  dbConnect();
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
